### ISSUE TITLE
Angle to the goal

### ISSUE THREAD

**Issue by vargac** [xlcteam/PixyViSy#19]
It  would be useful to also get angle to the goal from PixyViSy, not only 'L' or 'R'. Lack of this feature leads to using `processBall()` for this purpose, what makes kind of mess in source code.

**Comment by JakubGal** [comment]
This is a good idea but it  would be necessary to add some switching to the processing function between the current method and the angle to avoid unnecessarily processing because of the deterioration of processing speed.

**Comment by vargac** [comment]
@JakubGal It's only one call to atan2 and one multiplication of floating point numbers, but thanks for mentioning, I will implement it as an extra option.

**Comment by vargac** [comment]
@JakubGal Please, have a look at #20

**Comment by vargac** [comment]
Solved by #20
