### ISSUE TITLE
Redefinition of F() macro

### ISSUE THREAD

**Issue by vargac** [xlcteam/PixyViSy#9]
Branch vargac/orange_ball, file PixyViSy.cpp, line 5
Arduino has it's own F() macro for storing integers in program memory. We shouldn't redefine it I think.

**Comment by mrshu** [comment]
@vargac Is that necessary? As in, why do we need to redefine it?

**Comment by vargac** [comment]
@mrshu It is used for defining camera focal length. I think there is no problem to name it FOC_LEN, or CAMERA_F, ...

**Comment by mrshu** [comment]
@vargac In that case, that makes a lot of sense and I am all for using a different name, like some of those you provided.

**Comment by vargac** [comment]
Closing issue, as the branch with this problem has been deleted
